---
name: Github Actions

on: [ push ]

jobs:
  build:
    name: Hello github actions
    runs-on: ubuntu-latest
    strategy:
      go: [ '1.8', '1.9.3', '1.10.x' ]
    steps:
      - uses: actions/checkout@master
      - name: Hello github actions
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go run main.go